#docker-compose up  - terminal
services:
  postgres:
    container_name: market_db
    image: postgres
    environment:
      POSTGRES_DB: "market"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5431:5432"
